__author__ = 'thorwhalen'





lu_name_x_dict = {
    u'a_ce_split': [u'aCESplit', u'ACE split'],
    u'account': [u'account', u'Account'],
    u'account_id': [u'accountID', u'Account ID'],
    u'ad': [u'ad', u'Ad'],
    u'ad_approval_status': [u'adApprovalStatus', u'Ad Approval Status'],
    u'ad_extension_id': [u'adExtensionID', u'Ad Extension ID'],
    u'ad_extension_type': [u'adExtensionType', u'Ad Extension Type'],
    u'ad_group': [u'adGroup', u'Ad group'],
    u'ad_group_id': [u'adGroupID', u'Ad group ID'],
    u'ad_group_state': [u'adGroupState', u'Ad group state'],
    u'ad_id': [u'adID', u'Ad ID'],
    u'ad_state': [u'adState', u'Ad state'],
    u'ad_type': [u'adType', u'Ad type'],
    u'added': [u'added', u'Added'],
    u'approval_status': [u'approvalStatus', u'Approval Status'],
    u'attribute_values': [u'attributeValues', u'Attribute Values'],
    u'audience': [u'audience', u'Audience'],
    u'audience_state': [u'audienceState', u'Audience state'],
    u'avg_cpc': [u'avgCPC', u'Avg. CPC'],
    u'avg_cpm': [u'avgCPM', u'Avg. CPM'],
    u'avg_cpp': [u'avgCPP', u'Avg. CPP'],
    u'avg_position': [u'avgPosition', u'Avg. position'],
    u'bidding_strategy': [u'biddingStrategy', u'Bidding strategy'],
    u'budget': [u'budget', u'Budget'],
    u'budget_explicitly_shared': [u'budgetExplicitlyShared',
                                  u'Budget explicitly shared'],
    u'budget_id': [u'budgetID', u'Budget ID'],
    u'budget_name': [u'budgetName', u'Budget Name'],
    u'budget_period': [u'budgetPeriod', u'Budget period'],
    u'budget_state': [u'budgetState', u'Budget state'],
    u'budget_usage': [u'budgetUsage', u'Budget usage'],
    u'business_phone_number': [u'businessPhoneNumber', u'Business phone number'],
    u'cpc_ace_indicator': [u'cPCACEIndicator', u'CPC ACE indicator'],
    u'cpm_ace_indicator': [u'cPMACEIndicator', u'CPM ACE indicator'],
    u'ctr_ace_indicator': [u'cTRACEIndicator', u'CTR ACE indicator'],
    u'call_fee': [u'callFee', u'Call fee'],
    u'caller_area_code': [u'callerAreaCode', u'Caller area code'],
    u'caller_country_code': [u'callerCountryCode', u'Caller country code'],
    u'campaign': [u'campaign', u'Campaign'],
    u'campaign_id': [u'campaignID', u'Campaign ID'],
    u'campaign_state': [u'campaignState', u'Campaign state'],
    u'campaigns': [u'campaigns', u'# Campaigns'],
    u'categories': [u'categories', u'Categories'],
    u'city': [u'city', u'City'],
    u'click_id': [u'clickId', u'Click Id'],
    u'click_type': [u'clickType', u'Click type'],
    u'clicks': [u'clicks', u'Clicks'],
    u'clicks_ace_indicator': [u'clicksACEIndicator', u'Clicks ACE indicator'],
    u'client_name': [u'clientName', u'Client name'],
    u'company_name': [u'companyName', u'Company name'],
    u'content_impr_share': [u'contentImprShare', u'Content Impr. share'],
    u'content_lost_is_budget': [u'contentLostISBudget',
                                u'Content Lost IS (budget)'],
    u'content_lost_is_rank': [u'contentLostISRank', u'Content Lost IS (rank)'],
    u'conv': [u'conv', u'Conv.'],
    u'conv1_per_click': [u'conv1PerClick', u'Conv. (1-per-click)'],
    u'conv1_per_click_ace_indicator': [u'conv1PerClickACEIndicator',
                                       u'Conv. (1-per-click) ACE indicator'],
    u'conv_many_per_click': [u'convManyPerClick', u'Conv. (many-per-click)'],
    u'conv_many_per_click_ace_indicator': [u'convManyPerClickACEIndicator',
                                           u'Conv. (many-per-click) ACE indicator'],
    u'conv_rate': [u'convRate', u'Conv. rate'],
    u'conv_rate1_per_click': [u'convRate1PerClick', u'Conv. rate (1-per-click)'],
    u'conv_rate1_per_click_ace_indicator': [u'convRate1PerClickACEIndicator',
                                            u'Conv. rate (1-per-click) ACE indicator'],
    u'conv_rate_many_per_click': [u'convRateManyPerClick',
                                  u'Conv. rate (many-per-click)'],
    u'conv_rate_many_per_click_ace_indicator': [u'convRateManyPerClickACEIndicator',
                                                u'Conv. rate (many-per-click) ACE indicator'],
    u'conversion_action_name': [u'conversionActionName',
                                u'Conversion action name'],
    u'conversion_optimizer_bid_type': [u'conversionOptimizerBidType',
                                       u'Conversion optimizer bid type'],
    u'conversion_tracker_id': [u'conversionTrackerId', u'Conversion Tracker Id'],
    u'conversion_tracking_purpose': [u'conversionTrackingPurpose',
                                     u'Conversion tracking purpose'],
    u'cost': [u'cost', u'Cost'],
    u'cost_ace_indicator': [u'costACEIndicator', u'Cost ACE indicator'],
    u'cost_conv1_per_click': [u'costConv1PerClick',
                              u'Cost / conv. (1-per-click)'],
    u'cost_conv1_per_click_ace_indicator': [u'costConv1PerClickACEIndicator',
                                            u'Cost/conv. (1-per-click) ACE indicator'],
    u'cost_conv_many_per_click': [u'costConvManyPerClick',
                                  u'Cost / conv. (many-per-click)'],
    u'cost_conv_many_per_click_ace_indicator': [u'costConvManyPerClickACEIndicator',
                                                u'Cost/conv. (many-per-click) ACE indicator'],
    u'country_territory': [u'countryTerritory', u'Country/Territory'],
    u'criteria_display_name': [u'criteriaDisplayName', u'Criteria Display Name'],
    u'criteria_type': [u'criteriaType', u'Criteria Type'],
    u'criterion_id': [u'criterionID', u'Criterion ID'],
    u'ctr': [u'ctr', u'CTR'],
    u'currency': [u'currency', u'Currency'],
    u'customer_id': [u'customerID', u'Customer ID'],
    u'day': [u'day', u'Day'],
    u'day_of_week': [u'dayOfWeek', u'Day of week'],
    u'default_max_cpc': [u'defaultMaxCPC', u'Default max. CPC'],
    u'delivery_method': [u'deliveryMethod', u'Delivery method'],
    u'description_line1': [u'descriptionLine1', u'Description line 1'],
    u'description_line2': [u'descriptionLine2', u'Description line 2'],
    u'destination_url': [u'destinationURL', u'Destination URL'],
    u'device': [u'device', u'Device'],
    u'device_preference': [u'devicePreference', u'Device preference'],
    u'display_network_max_cpc': [u'displayNetworkMaxCPC',
                                 u'Display Network max. CPC'],
    u'display_url': [u'displayURL', u'Display URL'],
    u'domain': [u'domain', u'Domain'],
    u'duration_seconds': [u'durationSeconds', u'Duration (seconds)'],
    u'dynamic_ad_target': [u'dynamicAdTarget', u'Dynamic ad target'],
    u'dynamically_generated_headline': [u'dynamicallyGeneratedHeadline',
                                        u'Dynamically generated Headline'],
    u'end_time': [u'endTime', u'End time'],
    u'enhanced': [u'enhanced', u'Enhanced'],
    u'enhanced_cpc_enabled': [u'enhancedCPCEnabled', u'Enhanced CPC enabled'],
    u'excluded': [u'excluded', u'Excluded'],
    u'exclusion': [u'exclusion', u'Exclusion'],
    u'explicitly_shared': [u'explicitlyShared', u'Explicitly shared'],
    u'feed_id': [u'feedID', u'Feed ID'],
    u'feed_item_id': [u'feedItemID', u'Feed item ID'],
    u'feed_item_status': [u'feedItemStatus', u'Feed item status'],
    u'feed_placeholder_type': [u'feedPlaceholderType', u'Feed placeholder type'],
    u'first_level_sub_categories': [u'firstLevelSubCategories',
                                    u'First level sub-categories'],
    u'first_page_cpc': [u'firstPageCPC', u'First page CPC'],
    u'free_click_rate': [u'freeClickRate', u'Free click rate'],
    u'free_click_type': [u'freeClickType', u'Free click type'],
    u'free_clicks': [u'freeClicks', u'Free clicks'],
    u'frequency': [u'frequency', u'Frequency'],
    u'highest_position': [u'highestPosition', u'Highest position'],
    u'hour_of_day': [u'hourOfDay', u'Hour of day'],
    u'image_ad_name': [u'imageAdName', u'Image ad name'],
    u'image_hosting_key': [u'imageHostingKey', u'Image hosting key'],
    u'impressions': [u'impressions', u'Impressions'],
    u'impressions_ace_indicator': [u'impressionsACEIndicator',
                                   u'Impressions ACE indicator'],
    u'invalid_click_rate': [u'invalidClickRate', u'Invalid click rate'],
    u'invalid_clicks': [u'invalidClicks', u'Invalid clicks'],
    u'is_negative': [u'isNegative', u'Is negative'],
    u'is_targetable': [u'isTargetable', u'Is Targetable'],
    u'keyword': [u'keyword', u'Keyword'],
    u'keyword_id': [u'keywordID', u'Keyword ID'],
    u'keyword_max_cpc': [u'keywordMaxCPC', u'Keyword max CPC'],
    u'keyword_placement': [u'keywordPlacement', u'Keyword / Placement'],
    u'keyword_placement_destination_url': [u'keywordPlacementDestinationURL',
                                           u'Keyword/Placement destination URL'],
    u'keyword_placement_state': [u'keywordPlacementState',
                                 u'Keyword/Placement state'],
    u'keyword_state': [u'keywordState', u'Keyword state'],
    u'keyword_text': [u'keywordText', u'Keyword text'],
    u'landing_page_title': [u'landingPageTitle', u'Landing Page Title'],
    u'location': [u'location', u'Location'],
    u'location_extension_source': [u'locationExtensionSource',
                                   u'Location Extension Source'],
    u'location_type': [u'locationType', u'Location type'],
    u'login_email': [u'loginEmail', u'Login email'],
    u'lowest_position': [u'lowestPosition', u'Lowest position'],
    u'match_type': [u'matchType', u'Match type'],
    u'max_cpa': [u'maxCPA', u'Max. CPA%'],
    u'max_cpa1_per_click': [u'maxCPA1PerClick', u'Max. CPA (1-per-click)'],
    u'max_cpc': [u'maxCPC', u'Max. CPC'],
    u'max_cpc_source': [u'maxCPCSource', u'Max CPC source'],
    u'max_cpm': [u'maxCPM', u'Max. CPM'],
    u'max_cpm_source': [u'maxCPMSource', u'Max CPM Source'],
    u'max_cpp': [u'maxCPP', u'Max. CPP'],
    u'member_count': [u'memberCount', u'Member Count'],
    u'metro_area': [u'metroArea', u'Metro area'],
    u'month': [u'month', u'Month'],
    u'month_of_year': [u'monthOfYear', u'Month of Year'],
    u'most_specific_location': [u'mostSpecificLocation',
                                u'Most specific location'],
    u'negative_keyword': [u'negativeKeyword', u'Negative keyword'],
    u'network': [u'network', u'Network'],
    u'network_with_search_partners': [u'networkWithSearchPartners',
                                      u'Network (with search partners)'],
    u'page': [u'page', u'Page'],
    u'phone_bid_type': [u'phoneBidType', u'Phone bid type'],
    u'phone_calls': [u'phoneCalls', u'Phone calls'],
    u'phone_cost': [u'phoneCost', u'Phone cost'],
    u'phone_impressions': [u'phoneImpressions', u'Phone impressions'],
    u'placement': [u'placement', u'Placement'],
    u'placement_state': [u'placementState', u'Placement state'],
    u'position_ace_indicator': [u'positionACEIndicator',
                                u'Position ACE indicator'],
    u'ptr': [u'ptr', u'PTR'],
    u'quality_score': [u'qualityScore', u'Quality score'],
    u'quarter': [u'quarter', u'Quarter'],
    u'reference_count': [u'referenceCount', u'Reference Count'],
    u'region': [u'region', u'Region'],
    u'relative_ctr': [u'relativeCTR', u'Relative CTR'],
    u'search_exact_match_is': [u'searchExactMatchIS', u'Search Exact match IS'],
    u'search_impr_share': [u'searchImprShare', u'Search Impr. share'],
    u'search_lost_is_budget': [u'searchLostISBudget', u'Search Lost IS (budget)'],
    u'search_lost_is_rank': [u'searchLostISRank', u'Search Lost IS (rank)'],
    u'search_term': [u'searchTerm', u'Search term'],
    u'second_level_sub_categories': [u'secondLevelSubCategories',
                                     u'Second level sub-categories'],
    u'shared_set_id': [u'sharedSetID', u'Shared Set ID'],
    u'shared_set_name': [u'sharedSetName', u'Shared Set Name'],
    u'shared_set_type': [u'sharedSetType', u'Shared Set Type'],
    u'start_time': [u'startTime', u'Start time'],
    u'state': [u'state', u'State'],
    u'status': [u'status', u'Status'],
    u'targeting_mode': [u'targetingMode', u'Targeting Mode'],
    u'this_extension_vs_other': [u'thisExtensionVsOther',
                                 u'This extension vs. Other'],
    u'time_zone': [u'timeZone', u'Time zone'],
    u'top_level_categories': [u'topLevelCategories', u'Top level categories'],
    u'top_of_page_cpc': [u'topOfPageCPC', u'Top of page CPC'],
    u'top_vs_side': [u'topVsSide', u'Top vs. side'],
    u'topic': [u'topic', u'Topic'],
    u'topic_state': [u'topicState', u'Topic state'],
    u'total_conv_value': [u'totalConvValue', u'Total conv. value'],
    u'total_cost': [u'totalCost', u'Total cost'],
    u'unique_users': [u'uniqueUsers', u'Unique Users'],
    u'url': [u'url', u'URL'],
    u'value_conv1_per_click': [u'valueConv1PerClick',
                               u'Value / conv. (1-per-click)'],
    u'value_conv_many_per_click': [u'valueConvManyPerClick',
                                   u'Value / conv. (many-per-click)'],
    u'view_through_conv': [u'viewThroughConv', u'View-through conv.'],
    u'view_through_conv_ace_indicator': [u'viewThroughConvACEIndicator',
                                         u'View-through conv. ACE indicator'],
    u'week': [u'week', u'Week'],
    u'year': [u'year', u'Year']}